/**
 * The in-rpx gateway entry must merge `sites.d/*.json` fragments exactly the
 * way ts-cloud's generated assembler did on the box, so a box switching from
 * the compiled launcher to the prebuilt `rpx gateway` binary sees the same
 * routes, cert set, ACME allowlist and origin guard.
 *
 * Parity is checked against the assembler itself: `assemblerSource` below is
 * the output of ts-cloud's `renderRpxAssembler(sitesDir, certsDir)`
 * (packages/ts-cloud/src/drivers/shared/rpx-gateway.ts at ts-cloud a817a794)
 * with two edits that cannot change the merged config: the `startProxies`
 * import and call are swapped for a default export of the config it would
 * have started, and dash punctuation in its comments and log strings is
 * normalized to hyphens. Fixtures are shaped like `buildRpxConfig`
 * output (static routes with the object form, a server-app route, an auto-www
 * redirect, productionCerts, onDemandTls, acmeChallengeWebroot, originGuard).
 */
import { afterEach, beforeEach, describe, expect, it, spyOn } from 'bun:test'
import { spawn } from 'node:child_process'
import * as fsp from 'node:fs/promises'
import * as os from 'node:os'
import * as path from 'node:path'
import * as process from 'node:process'
import { mergeGatewayFragments, readGatewayFragments, resolveGatewayOptions, startGateway } from '../src/gateway'
import * as Start from '../src/start'

const CERTS_DIR = '/etc/rpx/certs'

let sitesDir: string

beforeEach(async () => {
  sitesDir = await fsp.mkdtemp(path.join(os.tmpdir(), 'rpx-gateway-sites-'))
})

afterEach(async () => {
  await fsp.rm(sitesDir, { recursive: true, force: true }).catch(() => {})
})

/** What `buildRpxConfig` emits for a Stacks app plus its docs, api and www. */
const STACKS_FRAGMENT = {
  slug: 'stacks',
  proxies: [
    { to: 'stacksjs.com', path: '/docs', static: { dir: '/var/www/stacks-docs/current', spa: false, pathRewriteStyle: 'directory' }, cleanUrls: true, id: 'stacksjs.com-docs' },
    { to: 'stacksjs.com', path: '/api', from: 'localhost:3000', id: 'stacksjs.com-api' },
    { to: 'stacksjs.com', static: { dir: '/var/www/stacks-public/current', spa: true, pathRewriteStyle: 'flat' }, cleanUrls: false, auth: { username: 'admin', password: 'hunter2' }, id: 'stacksjs.com' },
    { to: 'www.stacksjs.com', redirect: { to: 'https://stacksjs.com' }, id: 'www.stacksjs.com' },
  ],
  productionCerts: { certsDir: CERTS_DIR, certsDirServerNames: ['stacksjs.com', 'www.stacksjs.com'] },
  onDemandTls: { enabled: true, allowedSuffixes: ['stacksjs.com', 'www.stacksjs.com'], email: 'ops@stacksjs.com', certsDir: CERTS_DIR, staging: false },
  acmeChallengeWebroot: '/var/www/acme-challenge',
  https: true,
  hostsManagement: false,
  cleanup: { hosts: false, certs: false },
  originGuard: { header: 'X-Origin-Verify', value: 'secret-a', hosts: ['stacksjs.com', 'www.stacksjs.com'] },
}

/** A second tenant: staging ACME, its own certs dir, a duplicate route id, a different guard secret. */
const BLOG_FRAGMENT = {
  slug: 'blog',
  proxies: [
    { to: 'blog.example.org', from: ['10.0.0.5:4000', '10.0.0.6:4000'], loadBalancer: { strategy: 'least-connections' }, id: 'blog.example.org' },
    // Same id as the stacks apex: the first writer (stacks.json) must win.
    { to: 'stacksjs.com', from: 'localhost:9999', id: 'stacksjs.com' },
    // No id: keyed by to + path.
    { to: 'blog.example.org', path: '/admin', from: 'localhost:4001' },
  ],
  productionCerts: { certsDir: '/srv/blog-certs', certsDirServerNames: ['blog.example.org'] },
  onDemandTls: { enabled: true, allowedSuffixes: ['blog.example.org'], email: 'blog@example.org', certsDir: '/srv/blog-certs', staging: true },
  acmeChallengeWebroot: '/srv/acme',
  https: true,
  hostsManagement: false,
  cleanup: { hosts: false, certs: false },
  originGuard: { header: 'X-Origin-Verify', value: 'secret-b', hosts: ['blog.example.org'] },
}

/** Verbatim `renderRpxAssembler(sitesDir, certsDir)` output, minus the rpx import and start call. */
function assemblerSource(dir: string, defaultCertsDir: string): string {
  return `// Generated by ts-cloud - rpx gateway assembler.
// Merges every app's fragment in ${dir} so independent deploys compose
// without clobbering each other. Each deploy writes only its own <slug>.json.
import { readdirSync, readFileSync } from 'node:fs'

const dir = ${JSON.stringify(dir)}
const proxies = []
const seen = new Set()
const owners = new Map()
const suffixes = new Set()
const guardHosts = new Set()
let email
let certsDir = ${JSON.stringify(defaultCertsDir)}
let acmeChallengeWebroot
let guard
let anyProduction = false
let files = []
try { files = readdirSync(dir).filter(n => n.endsWith('.json')).sort() } catch {}
for (const f of files) {
  let frag
  // Fragments are written atomically (temp + rename by ts-cloud), so a parse
  // failure here means a genuinely corrupt fragment, not a mid-write read. Log
  // it LOUD - a silent skip drops that app's whole host from the routing table,
  // which then answers 404 until someone notices. We still continue so one bad
  // fragment can't take every other app down, but the drop is now visible.
  try { frag = JSON.parse(readFileSync(dir + '/' + f, 'utf8')) }
  catch (err) { console.error('[rpx-assembler] SKIPPING malformed fragment ' + f + ' - its host(s) will 404 until fixed: ' + err); continue }
  for (const p of frag.proxies ?? []) {
    const key = p.id || (p.to + (p.path ?? ''))
    if (seen.has(key)) {
      console.warn('[rpx-assembler] duplicate route ' + key + ' in ' + f + ' ignored; first declared by ' + owners.get(key))
      continue
    }
    seen.add(key)
    owners.set(key, f)
    proxies.push(p)
  }
  for (const s of frag.onDemandTls?.allowedSuffixes ?? []) suffixes.add(s)
  email ??= frag.onDemandTls?.email
  // One gateway, one ACME directory: production wins any disagreement between
  // co-tenants, and a fragment predating the flag counts as production. A
  // staging cert chains to an untrusted root, so defaulting the other way
  // breaks every client of every tenant that wanted a real cert.
  if (frag.onDemandTls && frag.onDemandTls.staging !== true) anyProduction = true
  if (frag.productionCerts?.certsDir) certsDir = frag.productionCerts.certsDir
  acmeChallengeWebroot ??= frag.acmeChallengeWebroot
  if (frag.originGuard) {
    // One gateway means one origin-guard secret (rpx takes a single
    // header/value). A tenant whose secret disagrees with the adopted one must
    // NOT have its hosts guarded: its CDN would send a different value, the
    // gateway would reject every request, and a working host would go dark.
    // Unguarded is weaker but serving, and the mismatch is logged.
    guard ??= { header: frag.originGuard.header, value: frag.originGuard.value }
    if (frag.originGuard.header === guard.header && frag.originGuard.value === guard.value) {
      for (const h of frag.originGuard.hosts ?? []) guardHosts.add(h)
    }
    else {
      console.warn('[rpx-assembler] origin-guard secret in ' + f + ' differs from the one already in force; its hosts stay unguarded rather than rejecting all traffic')
    }
  }
}
const config = {
  proxies,
  productionCerts: {
    certsDir,
    // A shared host's cert directory also contains mail and retired-site PEMs.
    // Keep those files on disk for their owners, but do not turn them into live
    // OpenSSL SNI contexts when no current route can select them.
    certsDirServerNames: [...new Set(proxies.map(p => p.to).filter(Boolean))],
  },
  https: true,
  hostsManagement: false,
  cleanup: { hosts: false, certs: false },
  // Verbose is the hard default for ts-cloud-installed gateways: without it,
  // rpx's TLS/routing diagnostics (tlsx on-demand 'refused issuance',
  // 'issuance failed', 'adopted existing on-disk cert') never reach the systemd
  // journal and a production TLS failure looks like "nothing happens". Silence
  // it by setting RPX_VERBOSE=false on the systemd unit.
  verbose: process.env.RPX_VERBOSE !== 'false',
  ...(suffixes.size > 0 ? { onDemandTls: { enabled: true, allowedSuffixes: [...suffixes], email, certsDir, staging: !anyProduction } } : {}),
  ...(acmeChallengeWebroot ? { acmeChallengeWebroot } : {}),
  ...(guard ? { originGuard: { header: guard.header, value: guard.value, hosts: [...guardHosts] } } : {}),
}

export default config
`
}

/** Run the copied assembler against `dir` and return the config it would have started. */
async function assemble(dir: string, defaultCertsDir: string): Promise<Record<string, unknown>> {
  // Inside the (per-test) sites dir: Bun caches directory listings during
  // module resolution, so a file that appears later in a shared parent is not
  // found. Neither reader picks it up (both filter on `.json`).
  const file = path.join(dir, `rpx-assembler-${Date.now()}.mjs`)
  await fsp.writeFile(file, assemblerSource(dir, defaultCertsDir))
  try {
    const mod = await import(file)
    return mod.default as Record<string, unknown>
  }
  finally {
    await fsp.rm(file, { force: true })
  }
}

async function writeFragments(): Promise<void> {
  await fsp.writeFile(path.join(sitesDir, 'blog.json'), JSON.stringify(BLOG_FRAGMENT, null, 2))
  await fsp.writeFile(path.join(sitesDir, 'stacks.json'), JSON.stringify(STACKS_FRAGMENT, null, 2))
  // Not a fragment: the assembler's `*.json` filter ignores an in-flight temp file.
  await fsp.writeFile(path.join(sitesDir, 'stacks.json.tmp-123'), '{ "proxies": [ { "to": "never.example" } ] }')
}

describe('readGatewayFragments', () => {
  it('reads *.json in filename order and yields nothing for a missing directory', async () => {
    await writeFragments()
    const fragments = await readGatewayFragments(sitesDir)
    expect(fragments.map(f => f.file)).toEqual(['blog.json', 'stacks.json'])
    expect(fragments[1].fragment.slug).toBe('stacks')
    expect(await readGatewayFragments(path.join(sitesDir, 'does-not-exist'))).toEqual([])
  })

  it('reports a malformed fragment and keeps the rest (never a silent drop)', async () => {
    await writeFragments()
    await fsp.writeFile(path.join(sitesDir, 'broken.json'), '{ "proxies": [ { "to": "x.example" ')
    await fsp.writeFile(path.join(sitesDir, 'array.json'), '[]')

    const errors: string[] = []
    const fragments = await readGatewayFragments(sitesDir, (file, err) => errors.push(`${file}: ${err.message}`))
    expect(fragments.map(f => f.file)).toEqual(['blog.json', 'stacks.json'])
    expect(errors).toHaveLength(2)
    expect(errors[0]).toStartWith('array.json: ')
    expect(errors[1]).toStartWith('broken.json: ')

    // The default handler writes to console.error, so the drop is visible in
    // the journal even when nobody wired a callback.
    const errorSpy = spyOn(console, 'error').mockImplementation(() => {})
    try {
      await readGatewayFragments(sitesDir)
      expect(errorSpy).toHaveBeenCalledTimes(2)
      expect(String(errorSpy.mock.calls[1][0])).toContain('SKIPPING malformed fragment broken.json')
    }
    finally {
      errorSpy.mockRestore()
    }
  })
})

describe('mergeGatewayFragments parity with the ts-cloud assembler', () => {
  it('produces the same config the generated assembler would have started', async () => {
    await writeFragments()
    await fsp.writeFile(path.join(sitesDir, 'broken.json'), 'not json')
    const warnSpy = spyOn(console, 'warn').mockImplementation(() => {})
    const errorSpy = spyOn(console, 'error').mockImplementation(() => {})
    try {
      const expected = await assemble(sitesDir, CERTS_DIR)
      const warnings: string[] = []
      const fragments = await readGatewayFragments(sitesDir, () => {})
      const merged = mergeGatewayFragments(fragments, { certsDir: CERTS_DIR, onWarning: m => warnings.push(m) })

      // Everything the assembler computed, byte for byte (verbose is added by
      // resolveGatewayOptions, not the merge).
      const { verbose, ...assembled } = expected
      expect(verbose).toBe(process.env.RPX_VERBOSE !== 'false')
      expect(merged).toEqual(assembled as typeof merged)

      // Spot-check the semantics the fixtures were built to exercise.
      const proxies = (merged as { proxies: Array<{ id?: string, to: string, path?: string, from?: unknown }> }).proxies
      expect(proxies.map(p => p.id ?? `${p.to}${p.path ?? ''}`)).toEqual([
        'blog.example.org',
        'stacksjs.com', // blog.json declares it first; stacks.json's copy is the duplicate
        'blog.example.org/admin',
        'stacksjs.com-docs',
        'stacksjs.com-api',
        'www.stacksjs.com',
      ])
      expect(proxies.find(p => p.id === 'stacksjs.com')!.from).toBe('localhost:9999')
      expect(merged.productionCerts).toEqual({ certsDir: CERTS_DIR, certsDirServerNames: ['blog.example.org', 'stacksjs.com', 'www.stacksjs.com'] })
      expect(merged.onDemandTls).toEqual({ enabled: true, allowedSuffixes: ['blog.example.org', 'stacksjs.com', 'www.stacksjs.com'], email: 'blog@example.org', certsDir: CERTS_DIR, staging: false })
      expect(merged.acmeChallengeWebroot).toBe('/srv/acme')
      expect(merged.originGuard).toEqual({ header: 'X-Origin-Verify', value: 'secret-b', hosts: ['blog.example.org'] })
      expect(merged.https).toBe(true)
      expect(merged.hostsManagement).toBe(false)
      expect(merged.cleanup).toEqual({ hosts: false, certs: false })
      expect(warnings).toEqual([
        'duplicate route stacksjs.com in stacks.json ignored; first declared by blog.json',
        'origin-guard secret in stacks.json differs from the one already in force; its hosts stay unguarded rather than rejecting all traffic',
      ])
      // The assembler logged the same two warnings and the malformed fragment.
      expect(warnSpy).toHaveBeenCalledTimes(2)
      expect(errorSpy).toHaveBeenCalledTimes(1)
    }
    finally {
      warnSpy.mockRestore()
      errorSpy.mockRestore()
    }
  })

  it('matches the assembler for a single production fragment too', async () => {
    await fsp.writeFile(path.join(sitesDir, 'stacks.json'), JSON.stringify(STACKS_FRAGMENT))
    const expected = await assemble(sitesDir, '/somewhere/else')
    const { verbose: _verbose, ...assembled } = expected
    const merged = mergeGatewayFragments(await readGatewayFragments(sitesDir), { certsDir: '/somewhere/else' })
    expect(merged).toEqual(assembled as typeof merged)
    // The fragment's own certsDir beats the fallback.
    expect(merged.productionCerts?.certsDir).toBe(CERTS_DIR)
    expect(merged.onDemandTls?.staging).toBe(false)
  })

  it('merges an empty registry to a routeless HTTPS gateway with no on-demand block', async () => {
    const expected = await assemble(sitesDir, CERTS_DIR)
    const { verbose: _verbose, ...assembled } = expected
    const merged = mergeGatewayFragments([], { certsDir: CERTS_DIR })
    expect(merged).toEqual(assembled as typeof merged)
    expect(merged.onDemandTls).toBeUndefined()
    expect(merged.originGuard).toBeUndefined()
  })
})

describe('resolveGatewayOptions', () => {
  it('applies the gateway switches on top of the merged fragments', async () => {
    await writeFragments()
    const resolved = await resolveGatewayOptions({
      sitesDir,
      certsDir: CERTS_DIR,
      https: false,
      httpPort: 8080,
      httpsPort: 8443,
      maxTlsContexts: 12,
      localCa: { dir: '/etc/rpx/local-ca', hosts: ['pi-stacks.local'], ips: ['192.168.1.20'] },
      verbose: false,
    })
    expect(resolved.https).toBe(false)
    expect(resolved.singlePortMode).toBe(true)
    expect(resolved.httpPort).toBe(8080)
    expect(resolved.httpsPort).toBe(8443)
    expect(resolved.maxTlsContexts).toBe(12)
    expect(resolved.localCa).toEqual({ dir: '/etc/rpx/local-ca', hosts: ['pi-stacks.local'], ips: ['192.168.1.20'] })
    expect(resolved.verbose).toBe(false)
    expect(resolved.hostsManagement).toBe(false)
    expect((resolved as { proxies: unknown[] }).proxies).toHaveLength(6)
  })

  it('defaults to HTTPS, verbose, and the fragments\' certs dir', async () => {
    await writeFragments()
    const resolved = await resolveGatewayOptions({ sitesDir })
    expect(resolved.https).toBe(true)
    expect(resolved.verbose).toBe(process.env.RPX_VERBOSE !== 'false')
    expect(resolved.httpPort).toBeUndefined()
    expect(resolved.localCa).toBeUndefined()
    expect(resolved.productionCerts?.certsDir).toBe(CERTS_DIR)
  })
})

describe('startGateway', () => {
  it('hands the merged options to startProxies', async () => {
    await writeFragments()
    const startSpy = spyOn(Start, 'startProxies').mockImplementation(async () => {})
    startSpy.mockClear()
    try {
      await startGateway({ sitesDir, https: false, httpPort: 8081, verbose: false })
      expect(startSpy).toHaveBeenCalledTimes(1)
      const [opts] = startSpy.mock.calls[0] as [{ https: unknown, httpPort: number, singlePortMode: boolean, proxies: unknown[] }]
      expect(opts.https).toBe(false)
      expect(opts.httpPort).toBe(8081)
      expect(opts.singlePortMode).toBe(true)
      expect(opts.proxies).toHaveLength(6)
    }
    finally {
      startSpy.mockRestore()
    }
  })
})

async function freePort(): Promise<number> {
  const probe = Bun.serve({ port: 0, hostname: '127.0.0.1', fetch: () => new Response('') })
  const port = probe.port as number
  probe.stop(true)
  return port
}

describe('rpx gateway (CLI, end to end)', () => {
  it('starts and prints its help', async () => {
    const cli = path.join(import.meta.dir, '..', 'bin', 'cli.ts')
    const child = spawn(process.execPath, [cli, '--help'], { stdio: ['ignore', 'pipe', 'pipe'] })
    let output = ''
    child.stdout?.on('data', (chunk: Buffer) => { output += chunk.toString() })
    child.stderr?.on('data', (chunk: Buffer) => { output += chunk.toString() })

    const exit = await Promise.race([
      new Promise<string>(resolve => child.once('exit', (code, signal) => resolve(`code=${code} signal=${signal}`))),
      new Promise<string>(resolve => setTimeout(() => resolve('still running after 45s'), 45_000)),
    ])

    if (child.exitCode === null && child.signalCode === null)
      child.kill('SIGKILL')

    expect(output, `rpx --help produced nothing (${exit})`).toContain('gateway')
  }, 60_000)

  it('serves a fragment\'s route over plain HTTP with --no-https on the given port', async () => {
    const upstream = Bun.serve({ port: 0, hostname: '127.0.0.1', fetch: req => new Response(`gateway-upstream ${req.headers.get('x-forwarded-host')}`) })
    const httpPort = await freePort()
    // Two routes so the fragment looks like a real box (and the shared
    // listener is exercised with Host-header routing).
    await fsp.writeFile(path.join(sitesDir, 'app.json'), JSON.stringify({
      slug: 'app',
      proxies: [
        { to: 'gw.test', from: `127.0.0.1:${upstream.port}`, id: 'gw.test' },
        { to: 'www.gw.test', redirect: { to: 'https://gw.test' }, id: 'www.gw.test' },
      ],
      productionCerts: { certsDir: path.join(sitesDir, 'certs'), certsDirServerNames: ['gw.test'] },
      https: true,
      hostsManagement: false,
      cleanup: { hosts: false, certs: false },
    }))

    const cli = path.join(import.meta.dir, '..', 'bin', 'cli.ts')
    const child = spawn(process.execPath, [cli, 'gateway', '--sites-dir', sitesDir, '--no-https', '--http-port', String(httpPort), '--https-port', String(httpPort + 1)], {
      stdio: ['ignore', 'pipe', 'pipe'],
      env: { ...process.env, RPX_VERBOSE: 'false', RPX_BIND_HOSTNAME: '127.0.0.1' },
    })
    let output = ''
    let spawnError: string | null = null
    let exited: string | null = null
    child.stdout?.on('data', (chunk: Buffer) => { output += chunk.toString() })
    child.stderr?.on('data', (chunk: Buffer) => { output += chunk.toString() })
    child.on('error', (err: Error) => { spawnError = `${err.name}: ${err.message}` })
    child.on('exit', (code: number | null, signal: string | null) => { exited = `code=${code} signal=${signal}` })

    try {
      let body: string | null = null
      const deadline = Date.now() + 45_000
      while (body === null && Date.now() < deadline) {
        try {
          const res = await fetch(`http://127.0.0.1:${httpPort}/hello`, {
            headers: { host: 'gw.test' },
            signal: AbortSignal.timeout(2000),
          })
          if (res.status === 200)
            body = await res.text()
          else
            await res.text().catch(() => {})
        }
        catch {
          // Not bound yet, or not answering yet.
        }
        if (body === null)
          await new Promise(resolve => setTimeout(resolve, 100))
      }
      const why = [
        `spawned: ${process.execPath} ${cli}`,
        spawnError ? `spawn error: ${spawnError}` : 'spawn error: none',
        exited ? `child exited early: ${exited}` : 'child still running',
        `child output: ${output || '(nothing)'}`,
      ].join('\n')
      expect(body, `gateway never served a response.\n${why}`).toBe('gateway-upstream gw.test')

      const redirected = await fetch(`http://127.0.0.1:${httpPort}/deep?x=1`, { headers: { host: 'www.gw.test' }, redirect: 'manual', signal: AbortSignal.timeout(5000) })
      expect(redirected.status).toBe(301)
      expect(redirected.headers.get('location')).toBe('https://gw.test/deep?x=1')

      const miss = await fetch(`http://127.0.0.1:${httpPort}/`, { headers: { host: 'other.test' }, signal: AbortSignal.timeout(5000) })
      expect(miss.status).toBe(404)

      // Nothing on the HTTPS port. Bounded, so a host that blackholes the
      // connection instead of refusing it fails the assertion rather than the
      // whole test file's timeout.
      await expect(fetch(`https://127.0.0.1:${httpPort + 1}/`, {
        tls: { rejectUnauthorized: false },
        signal: AbortSignal.timeout(5000),
      })).rejects.toThrow()
    }
    finally {
      if (child.exitCode === null && child.signalCode === null) {
        child.kill('SIGTERM')
        await Promise.race([
          new Promise(resolve => child.once('exit', resolve)),
          new Promise(resolve => setTimeout(resolve, 5000)),
        ])
      }
      upstream.stop(true)
    }
  }, 90_000)
})
